const { test, expect } = require('@playwright/test');
const { expectNoPageOverflow } = require('./helpers');
test('invited teacher gets games workspace, can return, and keeps account on upgrade',async({page,browser},testInfo)=>{
  const admin=await browser.newContext();
  let auth=await admin.request.post('/api/signup',{data:{name:'Games Admin',email:'games-admin@example.test',password:'Test-password-123!'}});
  if(!auth.ok())auth=await admin.request.post('/api/login',{data:{email:'games-admin@example.test',password:'Test-password-123!'}});
  expect(auth.ok()).toBeTruthy();
  const inv=await admin.request.post('/api/admin/teacher-invites',{data:{mode:'games'}});
  expect(inv.ok()).toBeTruthy();const {invite}=await inv.json();
  await page.goto('/welcome-games.html?invite='+invite.code);
  await expect(page.getByRole('link',{name:'Create account / sign in'})).toBeVisible();
  await expectNoPageOverflow(page);
  await page.screenshot({path:testInfo.outputPath('welcome.png'),fullPage:true});
  const signup=await page.request.post('/api/signup',{data:{name:'New Games Teacher',email:`games-${Date.now()}-${Math.random()}@example.test`,password:'Test-password-123!'}});
  const {user}=await signup.json();
  await page.getByRole('link',{name:'Create account / sign in'}).click();
  await expect(page.locator('#gamesWelcome')).toBeVisible();
  await expect(page.locator('#homeBtn')).toBeHidden();
  await expect(page.locator('#assignmentsBtn')).toBeHidden();
  expect((await page.request.get('/api/templates')).status()).toBe(403);
  expect((await page.request.get('/api/games')).ok()).toBeTruthy();
  expect((await page.request.get('/api/admin/teacher-invites')).status()).toBe(403);
  await page.locator('[data-game="colonyquest"]').click();
  await expect(page.locator('#pptxGameMode')).toHaveValue('colonyquest');
  await expect(page.locator('#pptxCreateBtn')).toBeVisible();
  await expect(page.locator('#pptxRosterPick')).toBeHidden();
  await page.locator('[data-game="fishquest"]').click();
  await expect(page.locator('#pptxRosterPick')).toBeVisible();
  await page.locator('[data-game="colonyquest"]').click();
  await page.locator('#pptxSubject').fill('Science');
  await page.locator('#pptxTopic').fill('Plants');
  await page.locator('#pptxFileInput').setInputFiles({name:'lesson.txt',mimeType:'text/plain',buffer:Buffer.from('Lesson notes: Plants need water and sunlight.')});
  const generated=page.waitForResponse(r=>r.url().endsWith('/api/game/from-pptx')&&r.request().method()==='POST');
  await page.locator('#pptxCreateBtn').click();
  const generatedResponse=await generated;expect(generatedResponse.ok()).toBeTruthy();
  const created=await generatedResponse.json();
  await expect(page.getByRole('link',{name:'Open ColonyQuest setup'})).toHaveAttribute('href',created.path);
  const gamesBefore=await (await page.request.get('/api/games')).json();
  expect(gamesBefore.games).toHaveLength(1);
  await expectNoPageOverflow(page);
  await page.screenshot({path:testInfo.outputPath('workspace.png'),fullPage:true});
  await page.reload();await expect(page.locator('#gamesWelcome')).toBeVisible();
  const saved=await page.request.post('/api/roster',{data:{name:'My retained class',rows:[{id:'TEST001',name:'Test Learner'}],idCol:'id',nameCol:'name'}});
  expect(saved.ok()).toBeTruthy();
  const before=await (await page.request.get('/api/rosters')).json();
  expect(before.rosters).toHaveLength(1);
  expect((await admin.request.post('/api/admin/teacher-invites/'+invite.code+'/upgrade',{data:{}})).ok()).toBeTruthy();
  await page.addInitScript(()=>localStorage.setItem('lc_wizard_done','1'));
  await page.reload();await expect(page.locator('#homeBtn')).toBeVisible();
  const me=await (await page.request.get('/api/me')).json();expect(me.user.id).toBe(user.id);expect(me.user.accessMode).toBe('full');
  expect(await (await page.request.get('/api/rosters')).json()).toEqual(before);
  expect(await (await page.request.get('/api/games')).json()).toEqual(gamesBefore);
  await admin.close();
});
test('invalid invitation shows a useful error and cannot continue',async({page})=>{
  await page.goto('/welcome-games.html?invite=not-real');
  await expect(page.locator('#status')).toContainText('invalid');
  await expect(page.locator('#start')).toHaveAttribute('aria-disabled','true');
});
