const {test,expect}=require('@playwright/test');
const {signInDisposableTeacher,expectNoPageOverflow}=require('./helpers');
const plan={sections:[{heading:'Starter',content:'Time: 15 minutes\nThink about senses.',stageId:'launch'},{heading:'Main Activity',content:'Time: 20 minutes\nMoonQuest task: minutes 15–30.',stageId:'practice'},{heading:'Independent Practice',content:'Time: 30 minutes\nApply learning.',stageId:'practice'},{heading:'Plenary',content:'Time: 5 minutes\nExit check.',stageId:'check'}],successCriteria:['I can explain which sense receives information.'],lessonPurpose:'lesson',teachingModelId:'standard'};
async function setup(page){await signInDisposableTeacher(page,'-design');await page.getByRole('button',{name:/Start with objectives/}).click();await page.locator('#subject').fill('ICT');await page.locator('#topic').fill('Senses');await page.locator('#flowSourceNextBtn').click();await page.locator('#objectives').fill('Identify senses and explain output devices.');await page.locator('#flowObjectivesNextBtn').click();}
test('duration, observation, game placement, manual slides and saved review survive reopening',async({page})=>{
 const errors=[];let reloading=false;page.on('pageerror',e=>{if(!(reloading&&e.message.includes('due to access control checks')))errors.push(e.message);});let sent;
 await page.route('**/api/lesson-plan',async route=>{sent=route.request().postDataJSON();await route.fulfill({json:plan});});
 await setup(page);await expect(page.locator('#plannedGameFields')).toBeHidden();
 await page.locator('#lessonMinutes').fill('70');await page.locator('#lessonMinutes').blur();await page.locator('#plannedGame').selectOption('moonquest');await page.locator('#plannedGameStart').fill('15');await page.locator('#observationEnabled').check();await page.locator('#slideCount').fill('12');await page.locator('#lessonMinutes').fill('75');await page.locator('#lessonMinutes').blur();await expect(page.locator('#slideCount')).toHaveValue('12');await page.locator('#lessonMinutes').fill('70');await page.locator('#lessonMinutes').blur();
 await expectNoPageOverflow(page);await page.locator('#planBtn').click();await expect(page.locator('#lessonDesignReview')).toContainText('MoonQuest: minute 15–30');expect(sent.lessonSettings.durationMinutes).toBe(70);expect(sent.lessonSettings.game.mode).toBe('moonquest');expect(sent.slideCount).toBe(12);await expect(page.locator('#reviewSlideCount')).toHaveValue('12');
 await page.locator('#reviewSlideCount').fill('14');await page.locator('#reviewSlideCount').blur();await page.evaluate(async()=>{clearTimeout(workspaceSaveTimer);await saveWorkspaceNow();});const id=await page.evaluate(()=>currentWorkspaceId);expect(id).toBeTruthy();reloading=true;await page.reload();reloading=false;await page.evaluate(id=>resumeLessonWorkspace(id),id);await expect(page.locator('#reviewSlideCount')).toHaveValue('14');await expect(page.locator('#lessonDesignReview')).toContainText('70-minute lesson');
 const popupPromise=page.waitForEvent('popup');await page.locator('#preparePlannedGame').click();const popup=await popupPromise;await expect(popup.locator('#mq-title')).toHaveValue('Senses');await expect(popup.locator('#mq-subject')).toHaveValue('ICT');await popup.close();expect(errors).toEqual([]);
});
test('server rejects impossible timing and unavailable saved games before generation',async({page})=>{await signInDisposableTeacher(page,'-invalid-design');for(const game of [{mode:'moonquest',startMinute:60,durationMinutes:15},{mode:'moonquest',startMinute:15,durationMinutes:15,existingId:'00000000-0000-4000-8000-000000000000'}]){const r=await page.request.post('/api/lesson-plan',{data:{subject:'ICT',topic:'Senses',objectives:'Explain senses',lessonSettings:{durationMinutes:70,game}}});expect(r.status()).toBe(400);}});
test('saved MoonQuest can be linked from review and another teacher cannot use it',async({page,browser},testInfo)=>{
 test.skip(testInfo.project.name!=='windows-100','Ownership is checked once against the real server.');
 await setup(page);await page.route('**/api/lesson-plan',r=>r.fulfill({json:plan}));await page.locator('#lessonMinutes').fill('70');await page.locator('#plannedGame').selectOption('moonquest');await page.locator('#plannedGameStart').fill('15');await page.locator('#planBtn').click();await expect(page.locator('#lessonDesignReview')).toBeVisible();
 const gamePage=await page.context().newPage();await gamePage.goto('/moonquest');await gamePage.getByRole('button',{name:'Try the senses example'}).click();await gamePage.locator('#reviewed').check();await gamePage.getByRole('button',{name:'Save adventure',exact:true}).click();await expect(gamePage.getByRole('button',{name:'Test game',exact:true})).toBeVisible();const lib=await(await page.request.get('/api/games/moonquest/library')).json();const id=lib.games[0].id;await gamePage.close();
 await page.locator('#linkPlannedGame').click();await expect(page.locator('#reviewLinkedGame')).toBeVisible();await page.locator('#reviewLinkedGame').selectOption(id);await expect(page.locator('#preparePlannedGame')).toHaveText('Open selected game');await page.evaluate(()=>saveWorkspaceNow());expect(await page.evaluate(()=>ctx.lessonSettings.game.existingId)).toBe(id);
 const other=await browser.newContext();const otherPage=await other.newPage();await signInDisposableTeacher(otherPage,'-foreign-game');const response=await otherPage.request.post('/api/lesson-plan',{data:{subject:'ICT',topic:'Senses',objectives:'Explain senses',lessonSettings:{durationMinutes:70,game:{mode:'moonquest',startMinute:15,durationMinutes:15,existingId:id}}}});expect(response.status()).toBe(400);expect((await response.json()).error).toContain('belonging to your account');await other.close();
});
