const {test,expect}=require('@playwright/test');const {signInDisposableTeacher}=require('./helpers');
test('25 learners on one network join, poll, answer and agree with the live analysis',async({page})=>{
 test.setTimeout(90000);await signInDisposableTeacher(page,'-classroom-load');await page.goto('/moonquest');await page.getByRole('button',{name:'Try the senses example'}).click();await page.locator('#reviewed').check();await page.getByRole('button',{name:'Save adventure',exact:true}).click();const lib=await(await page.request.get('/api/games/moonquest/library')).json();const game=await(await page.request.get('/api/games/moonquest/games/'+lib.games[0].id)).json();
 const prefix='LOAD'+Date.now();const roster=await(await page.request.post('/api/roster',{data:{name:'Full classroom',idCol:'id',nameCol:'name',rows:Array.from({length:25},(_,i)=>({id:prefix+i,name:'Learner '+i}))}})).json();
 const session=await(await page.request.post('/api/games/moonquest/games/'+game.game.id+'/sessions',{data:{rosterId:roster.id,mode:'duels'}})).json();const base='/api/games/moonquest/sessions/'+session.id;
 async function state(){return (await page.request.get(base+'/teacher')).json();}async function command(action){const s=await state();const r=await page.request.post(base+'/command',{data:{action,seq:s.seq}});expect(r.ok()).toBeTruthy();return r.json();}
 const initial=await state();await command('open-joining');
 // Repeated room discovery does not consume the shared PIN/sign-in allowance.
 const discoveries=await Promise.all(Array.from({length:90},()=>page.request.get('/api/games/moonquest/rooms/'+initial.code)));expect(discoveries.every(r=>r.ok())).toBe(true);
 const room=await discoveries[0].json();const joins=await Promise.all(room.students.map(st=>page.request.post(base+'/join',{data:{handle:st.handle,pin:'4738'}})));expect(joins.every(r=>r.ok())).toBe(true);const tokens=await Promise.all(joins.map(async r=>(await r.json()).token));expect((await state()).joined).toBe(25);
 await command('next');await expect.poll(async()=>(await state()).phase).toBe('choose');
 const times=[];const polls=await Promise.all(tokens.map(async token=>{const start=Date.now();const r=await page.request.get(base+'/state',{headers:{Authorization:'Bearer '+token}});times.push(Date.now()-start);expect(r.ok()).toBe(true);return r.json();}));expect(polls.every(s=>s.canAnswer&&s.phase==='choose')).toBe(true);
 const q=game.game.questions.find(q=>q.id===polls[0].question.id);const answers=await Promise.all(tokens.map((token,i)=>page.request.post(base+'/answer',{headers:{Authorization:'Bearer '+token},data:{round:0,phase:'choose',regionIds:q.answerMode==='all'?q.accepted:[q.accepted[0]],eventId:'load-'+i}})));expect(answers.every(r=>r.ok())).toBe(true);expect((await state()).answered).toBe(25);
 const grant=await(await page.request.post(base+'/observer-link',{data:{}})).json();const headers={Authorization:'Bearer '+grant.token};let analysis=await(await page.request.get(base+'/observe',{headers})).json();expect(analysis.rounds).toHaveLength(0);await command('advance');analysis=await(await page.request.get(base+'/observe',{headers})).json();expect(analysis.rounds[0].finalCorrect).toBe(25);expect(analysis.rounds[0].missing).toBe(0);expect(analysis.totals).toEqual((await(await page.request.get(base+'/report')).json()).summary.totals);
 times.sort((a,b)=>a-b);console.log('Classroom burst: 25 sign-ins, 25 polls, 25 answers; local poll p95 '+times[Math.floor(times.length*.95)]+'ms');
});
