const {test,expect}=require('@playwright/test');const {signInDisposableTeacher}=require('./helpers');
test('teams and attendance precede sign-in and membership persists to the next duel',async({page,browser})=>{
 await signInDisposableTeacher(page,'-class-teams');await page.goto('/moonquest');await page.getByRole('button',{name:'Try the senses example'}).click();await page.locator('#reviewed').check();await page.getByRole('button',{name:'Save adventure',exact:true}).click();
 const library=await(await page.request.get('/api/games/moonquest/library')).json();const prefix='TEAM'+Date.now();const roster=await(await page.request.post('/api/roster',{data:{name:'Team class',idCol:'id',nameCol:'name',rows:Array.from({length:5},(_,i)=>({id:prefix+i,name:'Learner '+i}))}})).json();
 const create=async()=>await(await page.request.post('/api/games/moonquest/games/'+library.games[0].id+'/sessions',{data:{rosterId:roster.id,mode:'duels'}})).json();const room=await create();const base='/api/games/moonquest/sessions/'+room.id;await page.goto('/moonquest?session='+room.id);await expect(page.getByRole('heading',{name:'Choose teams before sign-in'})).toBeVisible();await expect(page.locator('.team-plan .team-person')).toHaveCount(5);
 let state=await(await page.request.get(base+'/teacher')).json();expect(state.joinOpen).toBe(false);
 const ctx=await browser.newContext();try{const learner=await ctx.newPage();await learner.goto('http://127.0.0.1:4341/moonquest/join?code='+state.code);await expect(learner.getByRole('heading',{name:'Your teacher is preparing the teams'})).toBeVisible();expect((await(await ctx.request.get('http://127.0.0.1:4341/api/games/moonquest/rooms/'+state.code)).json()).students).toEqual([]);
 const absent=state.teamRoster.find(st=>state.teamRoster.filter(x=>x.team===st.team).length===3);await page.locator('.team-plan [data-remove-learner="'+absent.id+'"]').click();await expect(page.locator('.team-plan .is-absent')).toHaveCount(1);await page.reload();await expect(page.locator('.team-plan .is-absent')).toHaveCount(1);
 await page.getByRole('button',{name:'Confirm teams & open sign-in'}).click();await expect(page.getByRole('heading',{name:'Meet your teams'})).toBeVisible();await learner.getByRole('button',{name:'Find my crew'}).click();await expect(learner.locator('[data-learner-handle]')).toHaveCount(4);
 state=await(await page.request.get(base+'/teacher')).json();const board=await ctx.newPage();await board.goto('http://127.0.0.1:4341/moonquest?session='+room.id+'&board='+state.boardToken);await expect(board.locator('.team-plan .team-person')).toHaveCount(4);await expect(board.locator('.team-plan')).not.toContainText(absent.name);await expect(board.getByRole('button',{name:'Mark absent'})).toHaveCount(0);
 const first=Object.fromEntries(state.teamRoster.map(st=>[st.id,st.team]));const second=await create();const next=await(await page.request.get('/api/games/moonquest/sessions/'+second.id+'/teacher')).json();expect(Object.fromEntries(next.teamRoster.map(st=>[st.id,st.team]))).toEqual(first);expect(next.teamRoster.every(st=>!st.removed)).toBe(true);expect(next.joinOpen).toBe(false);
 await page.screenshot({path:'/tmp/moonquest-team-setup.png',fullPage:true});
 }finally{await ctx.close();}
});
