const {test}=require('node:test');const assert=require('node:assert/strict');const duel=require('../moonquest-duels');
const right=(q,a)=>a==='a';
function room(n=4){const students=Array.from({length:n},(_,i)=>({id:'s'+i,name:'Learner '+i}));return {students,duels:{teams:Object.fromEntries(students.map((s,i)=>[s.id,i%2])),avatars:{}},game:{questions:[1,2]},round:0,rounds:[],phase:'choose'};}
function round(s,events){const r={expected:s.students.map(s=>s.id),answers:{},question:{},events:[],revealedAt:10000};for(const [id,at,answer='a']of events){r.answers[id]={final:answer};r.events.push({studentId:id,at});}r.duelGroups=duel.pair(s,r.expected);s.rounds.push(r);return r;}
test('balanced teams retain every learner and rotate cross-team opponents',()=>{const s=room(6);const a=duel.pair(s,s.students.map(s=>s.id));s.round=1;const b=duel.pair(s,s.students.map(s=>s.id));assert.equal(a.flat().length,6);assert.notDeepEqual(a,b);for(const group of a)assert.equal(new Set(group.map(id=>s.duels.teams[id])).size,2);const setup=duel.create(s.students);assert.equal(Object.values(setup.teams).filter(t=>t===0).length,3);});
test('odd and unequal crews keep every learner exactly once',()=>{for(const n of [1,3,5,25]){const s=room(n),groups=duel.pair(s,s.students.map(s=>s.id));assert.equal(new Set(groups.flat()).size,n);assert.equal(groups.flat().length,n);}const s=room(8);s.duels.teams.s1=0;s.duels.teams.s3=0;assert.equal(duel.pair(s,s.students.map(s=>s.id)).flat().length,8);});
test('speed is server timed, both correct within a second earn the bonus',()=>{const s=room();const r=round(s,[['s0',100],['s1',1100],['s2',100],['s3',1201]]);const v=duel.score(s,r,right);assert.equal(v.s0.points,120);assert.equal(v.s1.points,120);assert.equal(v.s2.points,120);assert.equal(v.s3.points,100);});
test('changed answers, wrong answers, unanswered and followups cannot earn speed',()=>{const s=room();const r=round(s,[['s0',100,'b'],['s0',200,'a'],['s1',1000,'a'],['s2',100,'b']]);let v=duel.score(s,r,right);assert.equal(v.s0.points,100);assert.equal(v.s1.points,120);assert.equal(v.s2.points,0);assert.equal(v.s3.points,0);r.question.parentId='prior';v=duel.score(s,r,right);assert.equal(v.s1.points,100);});
test('team progress is normalized and unrevealed answers stay private',()=>{const s=room(5);const r=round(s,s.students.map(st=>[st.id,100]));let v=duel.snapshot(s,'s0','student',right);assert.equal(v.teams[0].points,120);assert.equal(v.teams[1].points,120);assert.equal(v.result.points,120);r.revealedAt=null;v=duel.snapshot(s,'s0','student',right);assert.equal(v.result,undefined);assert.equal(v.teams[0].points,0);assert.equal(v.opponents[0].correct,undefined);assert.equal(v.assignments,undefined);});
test('removed learners do not cause score errors and solo learners get no speed',()=>{const s=room(2);const r=round(s,[['s0',100]]);r.expected=['s0'];assert.equal(duel.score(s,r,right).s0.points,100);assert.doesNotThrow(()=>duel.snapshot(s,'s0','student',right));});
test('final podium uses revealed rounds only, shares ties, and excludes removed learners',()=>{const s=room(8);round(s,[['s0',100],['s2',100],['s4',100],['s6',100],['s1',100,'b']]);const unfinished=round(s,[['s1',100]]);unfinished.revealedAt=null;s.phase='ended';s.removedStudents=['s6'];const v=duel.snapshot(s,'s0','student',right);assert.equal(v.winner,0);assert.equal(v.celebration[0].members.length,3);assert.deepEqual(v.celebration[0].podium.map(h=>h.rank),[1,1,1]);assert.equal(v.celebration[1].members[0].points,0);assert.deepEqual(v.celebration[1].podium,[]);s.phase='choose';assert.equal(duel.snapshot(s,'s0','student',right).celebration,undefined);});
test('finishing before the first answer reveals no invented winner podium',()=>{const s=room();s.phase='ended';const v=duel.snapshot(s,'s0','student',right);assert.equal(v.rounds,0);assert.ok(v.celebration.every(c=>!c.members.length&&!c.podium.length));});
